--- 
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: pg
  namespace: fda-eks-ns
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      applicationid: ap127322
      environment: dev
      role: pg
  serviceName: pg-svc
  template: 
    metadata: 
      labels: 
        applicationid: ap127322
        environment: dev
        role: pg
    spec: 
      containers: 
        - 
          env: 
            - 
              name: POSTGRES_PASSWORD
              value: test1234
          image: "fcr-nonprod.fmr.com/postgres:9.6"
          name: pg
          ports: 
            - 
              containerPort: 5432
          volumeMounts: 
            - 
              mountPath: /var/lib/postgresql/data
              name: pg-persistent-storage
              subPath: postgres
      imagePullSecrets: 
        - 
          name: regcred
      serviceAccountName: pg-access
  volumeClaimTemplates: 
    - 
      metadata: 
        name: pg-persistent-storage
        namespace: fda-eks-ns
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 10Gi
        storageClassName: gp2-encrypt

