---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg-role  ##This can be any name you define for your mongo role
  namespace: fda-eks-ns
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services"]
  verbs: [ "get", "list", "watch"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pg-role-binding   ##This can be any name you define for your mongo role binding
  namespace: fda-eks-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pg-role
subjects:
- kind: ServiceAccount
  name: pg-access    ##This has to be service account which was created in earlier step
  namespace: fda-eks-ns
